Credinissan.Affinity.Web/Models/Cotizacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// Credinissan.Affinity.Web.Models ROD acampos2
/// </summary>
namespace Credinissan.Affinity.Web.Models
{

    public class ModifiedFeeValues
    {
        public int FeeNumber { get; set; }
        public double FeeAmount { get; set; }
    }

    public class ItemTablaDesarrollo
    {

        public int Mes { get; set; }
        public DateTime Vencimiento { get; set; }
        public double Saldo { get; set; }
        public double Interes { get; set; }
        public double Capital { get; set; }
        public double Cuota { get; set; }
        public bool CuotaFija { get; set; }


    }

    public class Seguro
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Description { get; set; }
        public string TipoFormula { get; set; }
        public double Valor { get; set; }
        public double MontoBruto { get; set; }
    }

    public class Accesorio
    {
        public string Codigo { get; set; }
        public double Valor { get; set; }

    }
    public class Cotizacion {

        public enum TipoCredito
        {
            Inteligente = 1,
            Convencional = 2,

        }

        public int IdVersion { get; set; }
        public DateTime FechaPagare { get; set; }
        public int ValorVehiculo { get; set; }
        public int Cantidad { get; set; }
        public int Pie { get; set; }
        public int Retoma { get; set; }
        public int SaldoPrecio { get; set; }
        public double Tasa { get; set; }
        public int Plazo { get; set; }
        public DateTime FechaPrimerVencimiento { get; set; }
        public TipoCredito Tipo { get; set; }
        public GastoOperacional GastoOperacional { get; set; }
        public int DiasDesfase { get; set; }
        public double MontoDesfase { get; set; }
        public double ITE { get; set; }
        public double MAF { get; set; }
        public double CAF { get; set; }
        public double VFMG { get; set; }
        public double ComisionDealer { get; set; }
        public List<ItemTablaDesarrollo> TablaDesarrollo { get; set; }
        public List<Seguro> Seguros { get; set; }
        public List<Accesorio> Accesorios { get; set; }

        public Cotizacion( DateTime fechaPagare, int valorVehiculo,int cantidad, int pie, int retoma,  int plazo, DateTime fechaPrimerVencimiento, TipoCredito tipoCredito, int idVersion, int vfmg=0, List<ModifiedFeeValues> pagoConvenido=null)
        {
            IdVersion = idVersion;
            FechaPagare = fechaPagare;
            ValorVehiculo = valorVehiculo;
            Cantidad = cantidad;
            Pie = pie;
            Retoma = retoma;
            SaldoPrecio = (valorVehiculo * cantidad) - pie - retoma;
            Plazo = plazo;
            FechaPrimerVencimiento = fechaPrimerVencimiento;
            DiasDesfase = (int)(fechaPrimerVencimiento - fechaPagare).TotalDays - 30;
            TablaDesarrollo = new List<ItemTablaDesarrollo>();
            Tipo = tipoCredito;
            Seguros = new List<Seguro>();
            Accesorios = new List<Accesorio>();

            if (Tipo == Cotizacion.TipoCredito.Inteligente)
            {
                Plazo++;
            }

            for (int i = 1; i <= Plazo; i++)
            { 
                TablaDesarrollo.Add(new ItemTablaDesarrollo { Mes=i, Vencimiento = fechaPrimerVencimiento.AddMonths(i-1), CuotaFija=false });
            }

            if (Tipo == Cotizacion.TipoCredito.Inteligente)
            {
                VFMG = (double)valorVehiculo * vfmg / 100;
                FijarUnaCuota(Plazo, VFMG);
            }

            if (pagoConvenido !=null && pagoConvenido.Any()) // Cuota variable
            {
                foreach (var item in pagoConvenido)
                {
                    FijarUnaCuota(item.FeeNumber, item.FeeAmount);
                }
                
            }


        }

        public void FijarUnaCuota(int mes, double cuota )
        {
            var item = this.TablaDesarrollo.FirstOrDefault(i => i.Mes.Equals(mes));
            item.Cuota = cuota;
            item.CuotaFija = true;

        
        }

        public double GenerarTabla(double cuota, double saldoFinal )
        {

            if (Math.Abs(saldoFinal) < 0.001)
                return 0;
            else
            {
                saldoFinal = CAF;
                foreach (var item in TablaDesarrollo)
                {
                    if (!item.CuotaFija)
                        item.Cuota = cuota;

                    item.Interes = saldoFinal * Tasa;
                    item.Capital = item.Cuota - item.Interes;
                    saldoFinal -= item.Capital;

                }

                return GenerarTabla(cuota + saldoFinal / Plazo/2, saldoFinal);

            }


        }

       

    }

    
    
}

Credinissan.Affinity.Web/Controllers/SolicitudController.cs
using Credinissan.Affinity.Web.Data.DataObject;
using Credinissan.Affinity.Web.Data.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Credinissan.Affinity.Web.Controllers
{
    public class SolicitudController : Controller
    {
        // GET: Solicitud
        public ActionResult Index(int idCotizacion)
        {
            Context context = new Context();

            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);

            if (cotizacion.Solicitud == null)
                cotizacion.Solicitud = new Solicitud();

            if (cotizacion.Solicitud.Contratantes == null)
            {
                cotizacion.Solicitud.Contratantes = new List<Contratante>();
                cotizacion.Solicitud.Contratantes.Add(new Contratante
                {
                    TipoContratante = Enums.TipoContratante.Titular,
                    Actividad = "PMO",
                    ApMaterno = "ZUÑIGA",
                    ApPaterno = "CERDA",
                    Comuna = context.Comunas.ToList().First(),
                    Direccion = "HOLANDA 1125",
                    Email = "ROD@APPFITME.COM",
                    FechaInicioActividad = DateTime.Now.AddYears(-2),
                    FechaNacimiento = DateTime.Now.AddYears(-30),
                    Nombre = "RODRIGO FRANCISCO",
                    NombreEmpleador = "NTFS RETAIL",
                    Rut = "12674021-2",
                    Renta = 3000000,
                    Telefono = 966597065, RutEmpleador="98000000-1"
                });
            }
            else 
            {

                cotizacion.Solicitud.Contratantes.Add(new Contratante { TipoContratante = Enums.TipoContratante.Aval });
            }


            ViewBag.Solicitud = cotizacion.Solicitud;
            ViewBag.IdCotizacion = idCotizacion;

            return View();
        }

        public ActionResult Create(int idCotizacion)
        {
            Context context = new Context();

            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);

            ViewBag.IdCotizacion = idCotizacion;

            return View();
        }


        [HttpPost]
        public ActionResult SaveContratante(int idCotizacion,int idContratante, string rut, string apPaterno, string apMaterno, string nombre, DateTime fechaNacimiento, Enums.Nacionalidad nacionalidad, Enums.EstadoCivil estadoCivil, string direccion, string comuna, string email, int telefono, string actividad, Enums.TipoTrabajador tipoTrabajador, int renta, DateTime fechaInicioActividad, string rutEmpleador, string nombreEmpleador, Enums.TipoContratante tipoContratante)
        {
            Context context = new Context();

            string[] aux = rut.Split('-');
            Enums.TipoPersona tipoPersona = int.Parse(aux[0]) < 50000000 ? Enums.TipoPersona.Natural : Enums.TipoPersona.Juridica;

            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);
            Contratante contratante = new Contratante();

            if (idContratante == 0)
            {
                contratante = new Contratante();

                if (cotizacion.Solicitud == null)
                    cotizacion.Solicitud = new Solicitud();
                if (cotizacion.Solicitud.Contratantes == null)
                    cotizacion.Solicitud.Contratantes = new List<Contratante>();

                cotizacion.Solicitud.Contratantes.Add(contratante);
            }
            else
                contratante = context.Contratantes.Find(idContratante);

            contratante.Rut = rut;
            contratante.ApPaterno = apPaterno;
            contratante.ApMaterno = apMaterno;
            contratante.Nombre = nombre;
            contratante.FechaNacimiento = fechaNacimiento;
            contratante.Nacionalidad = nacionalidad;
            contratante.EstadoCivil = estadoCivil;
            contratante.Direccion = direccion;
            contratante.Comuna = context.Comunas.FirstOrDefault(c => c.Nombre.Equals(comuna));
            contratante.Email = email;
            contratante.Renta = renta;
            contratante.Telefono = telefono;
            contratante.Actividad = actividad;
            contratante.TipoTrabajador = tipoTrabajador;
            contratante.FechaInicioActividad = fechaInicioActividad;
            contratante.RutEmpleador = rutEmpleador;
            contratante.NombreEmpleador = nombreEmpleador;
            contratante.TipoContratante = tipoContratante;
            contratante.TipoPersona = tipoPersona;

            context.SaveChanges();

            return RedirectToAction("Index", new { idCotizacion });
        }

        [HttpPost]
        public ActionResult SendToEvaluate(int idCotizacion)
        {
            Context context = new Context();
            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);

            cotizacion.Solicitud.EstadoSolicitud = Enums.EstadoSolicitud.EnEvaluacion;
            cotizacion.Solicitud.FechaEnvioSolicitud = DateTime.Now;
            cotizacion.Solicitud.UsuarioSolicitante = context.Usuarios.FirstOrDefault(u => u.Username.Equals(User.Identity.Name));

            context.SaveChanges();

            return RedirectToAction("Status", new { idCotizacion });

        }
        public ActionResult Status(int idCotizacion)
        {
            Context context = new Context();
            ViewBag.Cotizacion = context.Cotizaciones.Find(idCotizacion);
            return View();

        }

       
        public JsonResult RefreshStatus(int idCotizacion)
        {
            Context context = new Context();
            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);

            //   //var data = { "programs": [{ "name": "zonealarm", "price": "500" }, { "name": "kaspersky", "price": "200" }] };

            return Json(new { 
                EstadoSolicitud= cotizacion.Solicitud.EstadoSolicitud.ToString(), 
                Comentario = cotizacion.Solicitud.ComentarioEvaluacion, 
                Documentos = cotizacion.Solicitud.DocumentosSolicitados ,  
                Motivos= cotizacion.Solicitud.MotivosRechazo}, JsonRequestBehavior.AllowGet);

        }

        public ActionResult AdjuntarDocumentos(int? id)
        {

            if (id == null)
            {

                if (Request.Files.Count > 0)
                {
                    GuardarImagen();
                }

                return Json("", JsonRequestBehavior.AllowGet);

            }


            Context context = new Context();
            ViewBag.Cotizacion = context.Cotizaciones.Find(id);

            return View();
        
        }


        [HttpPost]
        public ActionResult ImageUpload()
        {

            string ruta = "";


            Context context = new Context();

            if (Request.Files.Count > 0)
            {
                GuardarImagen();
            }

            return Json("", JsonRequestBehavior.AllowGet);

        }

        private void GuardarImagen()
        {
            Context context = new Context();

            var file = Request.Files[0];
            var ruta = "";
            if (file != null && file.ContentLength > 0)
            {

                var fileName = Path.GetFileName(file.FileName);
                var path = "";
                //if (gUser.Tipo == GUser.GEnums.TipoUsuario.Alumno)
                //{
                //    string urlImgClientes = ConfigurationManager.AppSettings["UrlImgClientes"];
                //    Cliente cliente = context.Clientes.Find(gUser.IdCliente);
                //    cliente.Foto = cliente.Id.ToString() + "_" + fileName;
                //    path = Path.Combine(Server.MapPath(urlImgClientes), cliente.Foto);
                //    file.SaveAs(path);
                //    string PathIMG = ConfigurationManager.AppSettings["PathIMG"];
                //    cliente.Imagen = System.IO.File.ReadAllBytes(PathIMG + "clientes\\" + cliente.Foto);
                //    gUser.Foto = urlImgClientes + "/" + cliente.Foto;

                //}
                //else
                //{
                //    string UrlImgUsuarios = ConfigurationManager.AppSettings["UrlImgUsuarios"];
                //    Usuario usuario = context.Usuarios.Find(gUser.IdUsuario);
                //    usuario.Foto = usuario.Id.ToString() + "_" + fileName;
                //    path = Path.Combine(Server.MapPath(UrlImgUsuarios), usuario.Foto);
                //    file.SaveAs(path);


                }
                context.SaveChanges();

            }

        



        #region en desuso 
        public JsonResult SaveContratante(int idCotizacion, string rut, string apPaterno,string apMaterno, string nombre, DateTime fechaNacimiento, Enums.Nacionalidad nacionalidad, Enums.EstadoCivil estadoCivil, string direccion, string comuna, string email, int telefono, string actividad, Enums.TipoTrabajador tipoTrabajador, int renta, DateTime fechaInicioActividad, string rutEmpleador, string nombreEmpleador, Enums.TipoContratante tipoContratante)
        {
            Context context = new Context();

            string[] aux = rut.Split('-');
            Enums.TipoPersona tipoPersona = int.Parse(aux[0]) < 50000000 ? Enums.TipoPersona.Natural : Enums.TipoPersona.Juridica;

            Cotizacion cotizacion = context.Cotizaciones.Find(idCotizacion);

            Contratante contratante = new Contratante
            {
                Rut = rut,
                ApPaterno = apPaterno,
                ApMaterno = apMaterno,
                Nombre = nombre,
                FechaNacimiento = fechaNacimiento,
                Nacionalidad =  nacionalidad,
                EstadoCivil = estadoCivil,
                Direccion = direccion,
                Comuna = context.Comunas.FirstOrDefault(c=> c.Nombre.Equals(comuna)),
                Email = email,
                Renta = renta,

Credinissan.Affinity.Web/Views/Cotizacion/Calculate.cshtml
@model Credinissan.Affinity.Web.Models.Cotizacion
@using Credinissan.Affinity.Web.Models

@{
    ViewBag.Title = "Calculate";
    Cotizacion cotizacion = Model;

    int PorcPie = (cotizacion.Pie + cotizacion.Retoma) * 100 / cotizacion.ValorVehiculo;
}

<style>

    .fila {
        height: 26px;
    }

    div span.etiqueta {
        color: #333;
        font-weight: 500;
        font-size: 15px;
    }

</style>
<h2 class="text-center w3-padding-32">Simulación de crédito automotriz</h2>

<div class="w3-padding-32">

    <hr />
    <table class="table">
        <tr>
            <td>

                <div class="fila"><span class="etiqueta">Valor Vehículo</span>: @cotizacion.ValorVehiculo.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">Pie</span>: @cotizacion.Pie.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">Retoma</span>: @cotizacion.Retoma.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">Saldo</span>: @cotizacion.SaldoPrecio.ToString("$#,0")</div>
                @if (cotizacion.Tipo == Cotizacion.TipoCredito.Convencional)
                {
                    <div class="fila"><span class="etiqueta">Plazo</span>: @cotizacion.Plazo meses </div>
                }
                else
                {
                    int plazo = cotizacion.Plazo - 1;
                    <div class="fila"><span class="etiqueta">Plazo</span>: @plazo meses + opción de compra </div>
                }
                <div class="fila"><span class="etiqueta">Tasa</span>: @cotizacion.Tasa.ToString("0.00%")</div>
                <div class="fila"><span class="etiqueta">Gasto Operacional</span>: @cotizacion.GastoOperacional.Items.Sum(g => g.Valor).ToString("$#,0")</div>

            </td>
            <td>
                <div class="fila"><span class="etiqueta">Desfase</span>: @cotizacion.MontoDesfase.ToString("$#,0") ( @cotizacion.DiasDesfase días ) </div>
                <div class="fila"><span class="etiqueta">ITE</span>: @cotizacion.ITE.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">MAF</span>: @cotizacion.MAF.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">CAF</span>: @cotizacion.CAF.ToString("$#,0")</div>
                @if (cotizacion.TablaDesarrollo != null)
                {
                    <div class="fila"><span class="etiqueta">Cuota</span>: @cotizacion.TablaDesarrollo.First().Cuota.ToString("$#,0")</div>
                }
                <div class="fila"><span class="etiqueta">VFMG</span>: @cotizacion.VFMG.ToString("$#,0")</div>
            </td>

        </tr>

    </table>



</div>

<div class="w3-padding-32">

    @Html.ActionLink("Continuar", "Solicitud", new { idCotizacion = ViewBag.IdCotizacion }, new { @Class = "btn btn-default btn-danger red-nissan" })
</div>


@if (cotizacion.TablaDesarrollo != null)
{<div class="w3-padding-32">

        <table class="table">
            <thead>
                <tr>
                    <td>Mes</td>
                    <td>Vencimiento</td>
                    <td>Capital</td>
                    <td>Interés</td>
                    <td>Cuota</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ItemTablaDesarrollo item in cotizacion.TablaDesarrollo)
                {

                    <tr>
                        <td>@item.Mes</td>
                        <td>@item.Vencimiento.ToShortDateString()</td>
                        <td>@item.Capital.ToString("#,#")</td>
                        <td>@item.Interes.ToString("#,#")</td>
                        <td>@item.Cuota.ToString("#,#")</td>
                    </tr>

                }

            </tbody>
        </table>

    </div>
}

<script src="~/Scripts/jquery-3.6.4.min.js"></script>
<script>

    $("#btnEnviar").click(function () {
        $.post("@Url.Action("SendCuotation")",null,
            function (data, status) {
                if (status == 'success')
                alert("Data: " + data.Data.msg );
            });
    });

</script>

Credinissan.Affinity.Web/Views/Cotizacion/Index.cshtml
@using Credinissan.Affinity.Web.Models;
@using Credinissan.Affinity.Web.Data.DataObject;
@{
    ViewBag.Title = "Cotización";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Producto> Productos = ViewBag.Productos;
    List<Modelo> modelos = ViewBag.Modelos;
}

@if (ViewBag.Error != null)
{

    <div class="alert alert-danger"> <i class="glyphicon glyphicon-exclamation-sign"></i> @ViewBag.Error</div>
}
@if (ViewBag.Exito != null)
{
    <div class="alert alert-success"><i class="glyphicon glyphicon-thumbs-up"></i>  @ViewBag.Exito</div>
}

@if (ViewBag.Info != null)
{

    <div class="alert alert-info">
        <i class="glyphicon glyphicon-info-sign"></i> @ViewBag.Info
    </div>

}

<div class="w3-padding-16">
    <h1>Cotización</h1>
</div>



<form action="/Cotizacion/Calculate" method="post" target="_self">

    <div class="w3-padding-32">

        <div class="row">
            <div class="col-md-4">
                <div class="w3-section">
                    <label>Año</label>
                    <input class="form-control" type="number" name="year" value="2023" required>
                </div>
            </div>
            <div class="col-md-4">
                <div class="w3-section">
                    <label>Modelo</label>
                    <select id="modelo" required name="modelo" class="form-control">
                        <option selected value=""0">Elige un modelo</option>
                        @foreach (Modelo modelo in modelos)
                        {
                            <option value="@modelo.Id">@modelo.Nombre</option>

                        }

                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="w3-section">
                    <label>Versión</label>
                    <div id="waitForVersion"></div>
                    <select id="version" required name="idVersion" class="form-control">
                       

                    </select>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="w3-section">
                    <div class="w3-section">
                        <label>Valor</label>
                        <input class="form-control" type="number" min="500000" max="100000000" id="valor" name="valorVehiculo" value="0" required>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="w3-section">
                    <div class="w3-section">
                        <label>Pie</label>
                        <input class="form-control" type="number" id="pie" name="pie" value="0" required>
                        <input type="hidden" id="retoma" name="retoma" value="0" required>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="w3-section">
                    <label>Monto del crédito</label>
                    <input class="form-control" type="number" id="monto"  value="0" readonly>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-md-4">

                <div class="w3-section">
                    <label>Producto</label>
                    <select name="idProducto" id="producto" class="form-control">
                        @foreach (Producto pro in ViewBag.Productos)
                        {
                            <option value="@pro.Id">@pro.Name</option>

                        }

                    </select>
                </div>

            </div>
            <div class="col-md-4">

                <div class="w3-section">
                    <label>Plazo</label>
                    <div id="waitForPlazo"></div>
                    <select name="plazo" id="plazo" class="form-control">
                    </select>
                </div>

            </div>

            <div class="col-md-4">
                <div class="w3-section">
                    <label>Vencimiento</label>
                    <input class="form-control" type="date" name="vencimiento" value="@DateTime.Today.AddMonths(1).ToString("yyyyy-MM-dd")" />
                </div>
            </div>


        </div>

    </div>
    <div class="w3-padding-64">
        <button type="submit" class="w3-button w3-block w3-padding-large red-nissan w3-margin-bottom">Calcular</button>
    </div>
</form>


<script src="~/Scripts/jquery-3.6.4.min.js"></script>

<script>

    $("#valor").change(function () {


        $("#monto").val($("#valor").val() - $("#pie").val());

    });

    $("#pie").change(function () {


        $("#monto").val($("#valor").val() - $("#pie").val());

    });

    function GetPlazos() {

         $('#plazo').empty();

         datos = {
            idProducto: $("#producto").val(),
        };

        $("#waitForPlazo").html('<img src="/Img/espere.gif" width="70" />');

        jQuery.ajax({
            type: "POST",
            url: "@Url.Action("GetPlazos")",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(datos),
            success: function (data) {

                data.data.forEach(element =>

                    $('#plazo').append("<option value='" + element.Id + "' >" + element.Id + "</option>")
                );

                $("#waitForPlazo").html('');

            },

            failure: function (errMsg) {
                alert(errMsg);

            }

        });

    }


    function GetVersiones() {

         $('#version').empty();

         datos = {
            idModelo: $("#modelo").val(),
        };

        $("#waitForVersion").html('<img src="/Img/espere.gif" width="70" />');

        jQuery.ajax({
            type: "POST",
            url: "@Url.Action("GetVersiones")",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(datos),
            success: function (data) {

                data.data.forEach(element =>

                    $('#version').append("<option value='" + element.Id + "' >" + element.Nombre + "</option>")
                );

                $("#waitForVersion").html('');

            },

            failure: function (errMsg) {
                alert(errMsg);

            }

        });

    }

    $("#producto").change(function () {

        GetPlazos();

    });


    $("#modelo").change(function () {

        GetVersiones();

    });


    $(document).ready(function () {

        GetPlazos();

    });


</script>

Credinissan.Affinity.Web/Views/Cotizacion/ResumenCotizacion.cshtml
@model Credinissan.Affinity.Web.Models.Cotizacion
@using Credinissan.Affinity.Web.Models
@{
    ViewBag.Title = "Simulación";
    Layout = "~/Views/Shared/_LayoutMailing.cshtml";

    Cotizacion cotizacion = Model;

}
<style>
    .fila {
        height: 26px;
    }

    div span.etiqueta {
        color: #333;
        font-weight: 500;
        font-size: 15px;
    }

    .text-center {
        text-align: center !important;
    }

    table {
        width: 100%;
        display: table;
        text-indent: initial;
        border-spacing: 2px;
        border-color: gray;
        caption-side: bottom;
        border-collapse: collapse;
        box-sizing: inherit;
    }

</style>

<h2 class="text-center w3-padding-32" >Simulación de crédito automotriz</h2>


<div class="w3-padding-32">
   
    <table class="table">
        <tr>
            <td>

                <div class="fila"><span class="etiqueta">Valor Vehículo</span>: @cotizacion.ValorVehiculo.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta" >Pie</span>: @cotizacion.Pie.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">Retoma</span>: @cotizacion.Retoma.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">Saldo</span>: @cotizacion.SaldoPrecio.ToString("$#,0")</div>
                @if (cotizacion.Tipo == Cotizacion.TipoCredito.Convencional)
                {
                    <div class="fila"><span class="etiqueta">Plazo</span>: @cotizacion.Plazo meses </div>
                }
                else
                {
                    int plazo = cotizacion.Plazo - 1;
                    <div class="fila"><span class="etiqueta">Plazo</span>: @plazo meses + opción de compra </div>
                }
                <div class="fila"><span class="etiqueta">Tasa</span>: @cotizacion.Tasa.ToString("0.00%")</div>
                <div class="fila"><span class="etiqueta">Gasto Operacional</span>: @cotizacion.GastoOperacional.Items.Sum(g => g.Valor).ToString("$#,0")</div>

            </td>
            <td>
                <div class="fila"><span class="etiqueta">Desfase</span>: @cotizacion.MontoDesfase.ToString("$#,0") ( @cotizacion.DiasDesfase días ) </div>
                <div class="fila"><span class="etiqueta">ITE</span>: @cotizacion.ITE.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">MAF</span>: @cotizacion.MAF.ToString("$#,0")</div>
                <div class="fila"><span class="etiqueta">CAF</span>: @cotizacion.CAF.ToString("$#,0")</div>
                @if (cotizacion.TablaDesarrollo != null)
                {
                    <div class="fila"><span class="etiqueta">Cuota</span>: @cotizacion.TablaDesarrollo.First().Cuota.ToString("$#,0")</div>
                }
                <div class="fila"><span class="etiqueta">VFMG</span>: @cotizacion.VFMG.ToString("$#,0")</div>
            </td>

        </tr>

    </table>



</div>

    @if (cotizacion.TablaDesarrollo != null)

    {<div class="w3-padding-32">

            <table class="table">
                <thead>
                    <tr>
                        <td>Mes</td>
                        <td>Vencimiento</td>
                        <td>Capital</td>
                        <td>Interés</td>
                        <td>Cuota</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ItemTablaDesarrollo item in cotizacion.TablaDesarrollo)
                    {

                        <tr>
                            <td>@item.Mes</td>
                            <td>@item.Vencimiento.ToShortDateString()</td>
                            <td>@item.Capital.ToString("#,#")</td>
                            <td>@item.Interes.ToString("#,#")</td>
                            <td>@item.Cuota.ToString("#,#")</td>
                        </tr>

                    }

                </tbody>
            </table>

        </div>
    }

Credinissan.Affinity.Web/Views/Cotizacion/correo.cshtml
@{
    ViewBag.Title = "correo";
    Layout = "~/Views/Shared/_LayoutMailing.cshtml";
}

<h2>correo</h2>